# Generated by Django 2.2.6 on 2019-11-03 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default='', max_length=100)),
                ('password', models.CharField(blank=True, default='', max_length=100)),
                ('firstname', models.CharField(blank=True, default='', max_length=100)),
                ('lastname', models.CharField(blank=True, default='', max_length=100)),
                ('grad_year', models.IntegerField()),
                ('gender', models.CharField(blank=True, default='', max_length=100)),
                ('school', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'ordering': ('firstname',),
            },
        ),
    ]
